# Generated by Django 4.2.2 on 2023-06-19 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='global.basemodel')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('primary_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('recaptcha', models.CharField(blank=True, max_length=255, null=True)),
                ('google_analytics', models.BooleanField(default=False)),
                ('gdpr_policy', models.BooleanField(default=False)),
                ('facebook_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=2083, null=True)),
            ],
            options={
                'db_table': 'GlobalSetting',
            },
            bases=('global.basemodel',),
        ),
        migrations.CreateModel(
            name='SmtpSetting',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='global.basemodel')),
                ('smtp_type', models.CharField(blank=True, max_length=10, null=True)),
                ('email_host', models.CharField(blank=True, max_length=48, null=True)),
                ('email_port', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email_host_user', models.CharField(blank=True, max_length=48, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=48, null=True)),
                ('default_from_email', models.CharField(blank=True, max_length=48, null=True)),
                ('global_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='global.globalsetting')),
            ],
            options={
                'db_table': 'SmtpSetting',
            },
            bases=('global.basemodel',),
        ),
    ]
