# Generated by Django 4.2.2 on 2023-06-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0002_language_audiobook_cover_image_bookcontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='paragraph_id',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='sentence_id',
            new_name='sentence',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='texts',
            new_name='line_text',
        ),
        migrations.AddField(
            model_name='page',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangabandhu.bookcontent'),
        ),
        migrations.AddField(
            model_name='page',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='line_serial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='total_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageaudio',
            name='line_break_sleep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
