# Generated by Django 4.2.2 on 2023-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0003_rename_paragraph_id_bookmark_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaudio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
