# Generated by Django 4.2.2 on 2023-07-07 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0007_remove_bookmark_page_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='audio_book',
        ),
        migrations.RemoveField(
            model_name='page',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_number',
        ),
        migrations.CreateModel(
            name='PageNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('audio_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_book_pages', to='bangabandhu.audiobook')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangabandhu.bookcontent')),
            ],
            options={
                'db_table': 'PageNumber',
            },
        ),
    ]
