# Generated by Django 4.2.2 on 2023-07-07 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0008_remove_page_audio_book_remove_page_chapter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagenumber',
            old_name='page_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='page',
            name='page_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangabandhu.pagenumber'),
        ),
    ]
