# Generated by Django 4.2.2 on 2023-07-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0009_rename_page_number_pagenumber_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageaudio',
            name='page',
        ),
        migrations.AddField(
            model_name='pageaudio',
            name='page_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_number_audio', to='bangabandhu.pagenumber'),
        ),
    ]
