# Generated by Django 4.2.2 on 2023-07-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0010_remove_pageaudio_page_pageaudio_page_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='PageLineSerial',
        ),
        migrations.AlterModelTable(
            name='pagelineserial',
            table='PageLineSerial',
        ),
    ]
