# Generated by Django 4.2.2 on 2023-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0011_rename_page_pagelineserial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='total_pages',
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
    ]
