# Generated by Django 4.2.2 on 2023-07-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0013_pagelineserial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagelineserial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pagelineserial',
            name='is_image',
        ),
        migrations.AddField(
            model_name='pageaudio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='line_image'),
        ),
        migrations.AddField(
            model_name='pageaudio',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
