# Generated by Django 4.2.2 on 2023-07-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangabandhu', '0014_remove_pagelineserial_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='page',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='line_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bangabandhu.pagelineserial'),
        ),
    ]
